export default {
  // Auth api end points
  register: 'login/registration',
  login: 'login',
  loginverify: 'otp',

  // Home api end points
  walletreport: 'wallet',
  paymentrequestreport: 'payment_request/report',
  rechargereport: 'recharge-report',
  service: 'get-services',
  commission: 'commission',
  packageinsert: 'package/add',
  packageupdate: 'package/update',
  package: 'package/report',
  commissionreport: 'commission/get',
  operator: 'operator',
  circle: 'get-circles',
  offercheck: 'offer-check',
  adduser: 'user/add',
  state: 'get-state',
  userreport: 'user/report',
  addcomplain: 'add-complain',
  complainreport: 'complain-report',
  changepassword: 'change_password',
  useredit: 'user/edit/',
  recharge: 'recharge',
  paymentdata: 'payment-data',
  addpaymentrequest: 'payment_request/add',
  userupdate: 'user/update',
  addcommissionupdate: 'commission/store',
  walletbalance: 'wallet-balance',
  changepin: 'change_pin',
  generateredirectlink: 'payment/generate-redirect-link',
};
